# Generated by Django 5.2.5 on 2025-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('original_language', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tmdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=500)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_countries', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-vote_count', '-vote_average'],
            },
        ),
    ]
