# Generated by Django 5.2.5 on 2025-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineValue', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
