# Generated by Django 5.2.5 on 2025-10-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineValue', '0004_liked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-vote_average'], name='CineValue_m_vote_av_1bf9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_count'], name='CineValue_m_vote_co_e9ced9_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='CineValue_m_tmdb_id_4d6e66_idx'),
        ),
    ]
