# Generated by Django 5.2.5 on 2025-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineValue', '0006_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDb250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rank', models.IntegerField(max_length=3)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('duration', models.CharField(max_length=15)),
                ('certificate', models.CharField(blank=True, max_length=15, null=True)),
                ('genres', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('movie_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IMDb Top 250 Movie',
                'verbose_name_plural': 'IMDb Top 250 Movies',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='CineValue_i_rank_38e513_idx'), models.Index(fields=['title'], name='CineValue_i_title_2746e2_idx')],
            },
        ),
    ]
