# Generated by Django 5.2.5 on 2025-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineValue', '0007_imdb250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
