# Generated by Django 5.2.5 on 2026-01-27 21:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CineValue', '0008_alter_movie_revenue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', config='english'), name='movie_title_ftx_inx'),
        ),
    ]
